module.exports = [
   {
  abortChances: {
  },

  id: "d1aa8603-5be7-4da0-88ea-6b9e3134cdf6",
  fullName: "Hurleigh Weatherhogg",
  email: "hweatherhogg0@sina.com.cn",
  ip: "184.107.201.217",
  language: "en-US",
  platform: "iOS",
  osName: "iOS",
  osVersion: "15.8.0",
  deviceManufacturer: "Apple",
  deviceModel: "iPhone 7",
  deviceHardware: "iPhone9,1",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: true,
  bundleIdentifier: "com.example.shop",
  appBuild: "189sa81m1abioaty",
  appVersion: "1.42.3",
  carrier: "Verizon",
  connectionType: "wifi",
  effectiveConnectionType: "3g",
  meta: {
    "feature.testGroup": "alpha"
  }
}, {
  abortChances: {
  },

  id: "4bcd7631-1054-45e9-94ce-dc239c53fb3c",
  fullName: "Lefty Bossingham",
  email: "lbossingham1@multiply.com",
  ip: "51.140.128.23",
  language: "en-GB",
  platform: "iOS",
  osName: "iOS",
  osVersion: "15.8.0",
  deviceManufacturer: "Apple",
  deviceModel: "iPhone 7",
  deviceHardware: "iPhone9,1",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "189sa81m1abioaty",
  appVersion: "1.42.3",
  carrier: "Verizon",
  connectionType: "cellular",
  effectiveConnectionType: "3g",
  meta: {
    "feature.testGroup": "beta"
  }
}, {
  abortChances: {
  },

  id: "4bcd7631-1054-45e9-94ce-dc239c53fb3c",
  fullName: "Francis Mart",
  email: "lbossingham1@multiply.com",
  ip: "51.140.128.23",
  language: "en-GB",
  platform: "iOS",
  osName: "iOS",
  osVersion: "15.8.0",
  deviceManufacturer: "Apple",
  deviceModel: "iPhone 7",
  deviceHardware: "iPhone9,1",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "189sa81m1abioaty",
  appVersion: "1.42.3",
  carrier: "Verizon",
  connectionType: "cellular",
  effectiveConnectionType: "3g",
  meta: {
    "feature.testGroup": "beta"
  }
}, {
  abortChances: {
  },

  id: "4bcd7631-1054-45e9-94ce-dc239c53fb3c",
  fullName: "marianne josh",
  email: "lbossingham1@multiply.com",
  ip: "51.140.128.23",
  language: "en-GB",
  platform: "iOS",
  osName: "iOS",
  osVersion: "16.7.1",
  deviceManufacturer: "Apple",
  deviceModel: "iPhone 13",
  deviceHardware: "iPhone14,5",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "189sa81m1abioaty",
  appVersion: "1.42.3",
  carrier: "Verizon",
  connectionType: "cellular",
  effectiveConnectionType: "3g",
  meta: {
    "feature.testGroup": "beta"
  }
}, {
  abortChances: {
  },

  id: "1bff1bbc-8e6e-410a-a7cf-a8dd88da3dca",
  fullName: "Berti Lethcoe",
  email: "blethcoe2@wordpress.com",
  ip: "239.178.221.197",
  language: "de-DE",
  platform: "iOS",
  osName: "iOS",
  osVersion: "16.7.1",
  deviceManufacturer: "Apple",
  deviceModel: "iPhone 13",
  deviceHardware: "iPhone14,5",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "189sa81m1abioaty",
  appVersion: "1.42.3",
  carrier: "Verizon",
  connectionType: "cellular",
  effectiveConnectionType: "3g",
  meta: {
    "feature.testGroup": "sigma"
  }
}, {
  abortChances: {
  },

  id: "b7b833ff-d9d8-4d82-95f2-a7f473405e9b",
  fullName: "Hi Navarre",
  email: "hnavarre3@arizona.edu",
  ip: "166.76.20.78",
  language: "de-DE",
  platform: "iOS",
  osName: "iOS",
  osVersion: "16.7.1",
  deviceManufacturer: "Apple",
  deviceModel: "iPhone 13",
  deviceHardware: "iPhone14,5",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "189sa81m1abioaty",
  appVersion: "1.42.3",
  carrier: "Verizon",
  connectionType: "cellular",
  effectiveConnectionType: "2g",
  meta: {
    "feature.testGroup": "alpha"
  }
}, {
  abortChances: {
  },

  id: "e409f571-b6a1-47ff-8c74-a273a7642f86",
  fullName: "Jaclyn Guarin",
  email: "jguarin4@ihg.com",
  ip: "178.69.53.149",
  language: "de-DE",
  platform: "iOS",
  osName: "iOS",
  osVersion: "16.7.1",
  deviceManufacturer: "Apple",
  deviceModel: "iPhone 13",
  deviceHardware: "iPhone14,5",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "189sa81m1abioaty",
  appVersion: "1.42.3",
  carrier: "Verizon",
  connectionType: "cellular",
  effectiveConnectionType: "2g",
  meta: {
    "feature.testGroup": "alpha"
  }
}, {
  abortChances: {
    payment: 1
  },

  id: "982bc0bd-95fd-423f-99b1-7ab3422296a8",
  fullName: "Dom Angus",
  email: "dangus5@homestead.com",
  ip: "197.54.174.148",
  language: "it",
  platform: "iOS",
  osName: "iOS",
  osVersion: "15.8.0",
  deviceManufacturer: "Apple",
  deviceModel: "iPhone 7",
  deviceHardware: "iPhone9,1",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "189sa81m1abioaty",
  appVersion: "1.42.3",
  carrier: "Verizon",
  connectionType: "cellular",
  effectiveConnectionType: "3g",
  meta: {
    "feature.testGroup": "alpha"
  }
}, {
  abortChances: {
  },

  id: "e8a6d74e-6bd2-42f5-9d50-b66f1f21a354",
  fullName: "Vernen Glaisner",
  email: "vglaisner6@mediafire.com",
  ip: "241.27.4.130",
  language: "it",
  platform: "iOS",
  osName: "iOS",
  osVersion: "15.8.0",
  deviceManufacturer: "Apple",
  deviceModel: "iPhone 7",
  deviceHardware: "iPhone9,1",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "189sa81m1abioaty",
  appVersion: "1.42.3",
  carrier: "Telekom",
  connectionType: "wifi",
  effectiveConnectionType: "4g",
  meta: {
    "feature.testGroup": "alpha"
  }
}, {
  abortChances: {
  },

  id: "9264d154-d538-4c2a-a65a-6dc25921142a",
  fullName: "Malina Waldron",
  email: "mwaldron7@guardian.co.uk",
  ip: "63.227.85.200",
  language: "en-US",
  platform: "iOS",
  osName: "iOS",
  osVersion: "15.8.0",
  deviceManufacturer: "Apple",
  deviceModel: "iPhone 7",
  deviceHardware: "iPhone9,1",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "189sa81m1abioaty",
  appVersion: "1.42.3",
  carrier: "Telekom",
  connectionType: "wifi",
  effectiveConnectionType: "3g",
  meta: {
    "feature.testGroup": "alpha"
  }
}, {
  abortChances: {
  },

  id: "974c5baf-6291-4868-bf60-cca4a51c0cd1",
  fullName: "Clea Ronchka",
  email: "cronchka8@senate.gov",
  ip: "124.140.49.153",
  language: "en-US",
  platform: "iOS",
  osName: "iOS",
  osVersion: "15.8.0",
  deviceManufacturer: "Apple",
  deviceModel: "iPhone 7",
  deviceHardware: "iPhone9,1",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "189sa81m1abioaty",
  appVersion: "1.42.3",
  carrier: "Sprint",
  connectionType: "cellular",
  effectiveConnectionType: "4g",
  meta: {
    "feature.testGroup": "alpha"
  }
}, {
  abortChances: {
  },

  id: "03f15da4-a316-4316-bffe-f5eceed78dd0",
  fullName: "Jemimah Gellately",
  email: "jgellately9@technorati.com",
  ip: "245.170.13.160",
  language: "sr-Latn-RS",
  platform: "iOS",
  osName: "iOS",
  osVersion: "15.8.0",
  deviceManufacturer: "Apple",
  deviceModel: "iPhone 7",
  deviceHardware: "iPhone9,1",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "189sa81m1abioaty",
  appVersion: "1.42.3",
  carrier: "Sprint",
  connectionType: "cellular",
  effectiveConnectionType: "4g",
  meta: {
    "feature.testGroup": "alpha"
  }
}, {
  abortChances: {
  },

  id: "0aadd067-6e57-4e10-84bf-8339827ae94a",
  fullName: "Arthur Lanon",
  email: "alanona@blogs.com",
  ip: "180.125.195.213",
  language: "en-US",
  platform: "iOS",
  osName: "iOS",
  osVersion: "15.8.0",
  deviceManufacturer: "Apple",
  deviceModel: "iPhone 7",
  deviceHardware: "iPhone9,1",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "189sa81m1abioaty",
  appVersion: "1.42.3",
  carrier: "Verizon",
  connectionType: "wifi",
  effectiveConnectionType: "4g",
  meta: {
    "feature.testGroup": "alpha"
  }
}, {
  abortChances: {
  },

  id: "ee961ac7-7849-40a6-acea-d71290ae2fdc",
  fullName: "Lucian Jaqueme",
  email: "ljaquemeb@phpbb.com",
  ip: "86.231.177.166",
  language: "en-US",
  platform: "iOS",
  osName: "iOS",
  osVersion: "15.8.0",
  deviceManufacturer: "Apple",
  deviceModel: "iPhone 7",
  deviceHardware: "iPhone9,1",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "189sa81m1abioaty",
  appVersion: "1.42.3",
  carrier: "Verizon",
  connectionType: "wifi",
  effectiveConnectionType: "4g",
  meta: {
    "feature.testGroup": "alpha"
  }
}, {
  abortChances: {
  },

  id: "fa2cd216-7c04-4bd6-b67e-85714004d53d",
  fullName: "Henri Wanden",
  email: "hwandenc@dailymotion.com",
  ip: "231.54.117.153",
  language: "en-US",
  platform: "iOS",
  osName: "iOS",
  osVersion: "16.7.1",
  deviceManufacturer: "Apple",
  deviceModel: "iPhone 13",
  deviceHardware: "iPhone14,5 ",
  viewportWidth: 280,
  viewportHeight: 580,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "189sa81m1abioaty",
  appVersion: "1.42.3",
  carrier: "Verizon",
  connectionType: "wifi",
  effectiveConnectionType: "4g",
  meta: {
    "feature.testGroup": "sigma"
  }
}, {
  abortChances: {
  },

  id: "cb221217-7d04-4bd6-b67m-85714bb4d53a",
  fullName: "Felix Müller",
  email: "felixmueller+demo@gmail.com",
  ip: "94.134.95.26",
  language: "de-DE",
  platform: "Android",
  osName: "Android",
  osVersion: "10",
  deviceManufacturer: "Google",
  deviceModel: "Google Pixel 4XL",
  deviceHardware: "Google Pixel 4XL",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "aba9031kl",
  appVersion: "1.41.4",
  carrier: "Deutsche Telekom",
  connectionType: "wifi",
  effectiveConnectionType: "3g",
  meta: {
    "feature.testGroup": "beta"
  }
}, {
  abortChances: {
  },

  id: "ac6519ab-a78b-4ad9-8189-22acfe5ef185",
  fullName: "Adullah Mohammed",
  email: "AbdullaMohammed@gmail.com",
  ip: "130.214.222.3",
  language: "ar-SA",
  latitude : 25.6537,
  longitude :  43.8873,
  accuracyRadius : 5,
  country : "Saudi Arabia",
  countryCode : "SA",
  continent : "Asia",
  continentCode : "AS",
  platform: "Android",
  osName: "Android",
  osVersion: "10",
  deviceManufacturer: "Google",
  deviceModel: "Google Pixel 4XL",
  deviceHardware: "Google Pixel 4XL",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "aba9031kl",
  appVersion: "1.41.4",
  carrier: "Saudi Telecom Company",
  connectionType: "cellular",
  effectiveConnectionType: "3g",
  playbook: 'warehouseCrash',
  meta: {
    "feature.testGroup": "beta"
  }
}, {
  abortChances: {
  },

  id: "7277bdc1-3bae-408c-897d-87fc136ed303",
  fullName: "Fadil Gabriel",
  email: "FadilGab128@gmail.com",
  ip: "103.152.99.13",
  language: "ar-BH",
  latitude : 26.0667,
  longitude :  50.557,
  accuracyRadius : 5,
  country : "Bahrain",
  countryCode : "BH",
  continent : "Asia",
  continentCode : "AS",
  platform: "Android",
  osName: "Android",
  osVersion: "10",
  deviceManufacturer: "Google",
  deviceModel: "Google Pixel 4XL",
  deviceHardware: "Google Pixel 4XL",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "aba9031kl",
  appVersion: "1.41.4",
  carrier: "Omantel",
  connectionType: "wifi",
  effectiveConnectionType: "3g",
  playbook: 'warehouseCrash',
  meta: {
    "feature.testGroup": "beta"
  }
}, {
  abortChances: {
  },

  id: "e8380340-4923-45dc-8efe-7f726b045e87",
  fullName: "Sana Zoravar",
  email: "Zoravarsana67@gmail.com",
  ip: "130.214.222.3",
  language: "ar-SA",
  latitude : 25.6537,
  longitude :  43.8873,
  accuracyRadius : 5,
  country : "Saudi Arabia",
  countryCode : "SA",
  continent : "Asia",
  continentCode : "AS",
  platform: "Android",
  osName: "Android",
  osVersion: "10",
  deviceManufacturer: "Google",
  deviceModel: "Google Pixel 4XL",
  deviceHardware: "Google Pixel 4XL",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "aba9031kl",
  appVersion: "1.41.4",
  carrier: "Saudi Telecom Company",
  connectionType: "cellular",
  effectiveConnectionType: "3g",
  playbook: 'warehouseCrash',
  meta: {
    "feature.testGroup": "beta"
  }
}, {
  abortChances: {
  },

  id: "fbe715ef-04b0-4bdb-89da-1f70bff0f640",
  fullName: "Razeem Afreen",
  email: "Razeemafreen97@gmail.com",
  ip: "82.148.96.34",
  language: "ar-QA",
  latitude : 25.3548,
  longitude :  51.1838,
  accuracyRadius : 5,
  country : "Qatar",
  countryCode : "QA",
  continent : "Asia",
  continentCode : "AS",
  platform: "Android",
  osName: "Android",
  osVersion: "10",
  deviceManufacturer: "Google",
  deviceModel: "Google Pixel 4XL",
  deviceHardware: "Google Pixel 4XL",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "aba9031kl",
  appVersion: "1.41.4",
  carrier: "Omantel",
  connectionType: "wifi",
  effectiveConnectionType: "3g",
  playbook: 'warehouseCrash',
  meta: {
    "feature.testGroup": "beta"
  }
}, {
  abortChances: {
  },

  id: "c803cdb1-e433-41cf-adb5-e1eb320656f2",
  fullName: "Zeeshan Malik",
  email: "Zeemalik@gmail.com",
  ip: "47.246.28.52",
  language: "ar-SA",
  latitude : 21.4735,
  longitude :  55.9754,
  accuracyRadius : 5,
  country : "Saudi Arabia",
  countryCode : "SA",
  continent : "Asia",
  continentCode : "AS",
  platform: "Android",
  osName: "Android",
  osVersion: "10",
  deviceManufacturer: "Google",
  deviceModel: "Google Pixel 4XL",
  deviceHardware: "Google Pixel 4XL",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "aba9031kl",
  appVersion: "1.41.4",
  carrier: "Saudi Telecom Company",
  connectionType: "cellular",
  effectiveConnectionType: "3g",
  playbook: 'warehouseCrash',
  meta: {
    "feature.testGroup": "beta"
  }
}, {
  abortChances: {
  },

  id: "0390db5d-a249-4cf6-a46a-6779b172d5b6",
  fullName: "Tabsheer Irfad",
  email: "Tabsheetirfad@gmail.com",
  ip: "78.159.160.12",
  language: "ar-KW",
  latitude : 29.3117,
  longitude :  47.4818,
  accuracyRadius : 5,
  country : "Kuwait",
  countryCode : "KW",
  continent : "Asia",
  continentCode : "AS",
  platform: "Android",
  osName: "Android",
  osVersion: "10",
  deviceManufacturer: "Google",
  deviceModel: "Google Pixel 4XL",
  deviceHardware: "Google Pixel 4XL",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "aba9031kl",
  appVersion: "1.41.4",
  carrier: "Omantel",
  connectionType: "wifi",
  effectiveConnectionType: "3g",
  playbook: 'warehouseCrash',
  meta: {
    "feature.testGroup": "beta"
  }
}, {
  abortChances: {
  },

  id: "70cd46a4-9342-462e-8479-e099d3c405c9",
  fullName: "Reyan Mallik",
  email: "Reyanmallik@gmail.com",
  ip: "144.220.138.12",
  language: "ar-BH",
  latitude : 26.0667,
  longitude :  50.5577,
  accuracyRadius : 5,
  country : "Bahrain",
  countryCode : "BH",
  continent : "Asia",
  continentCode : "AS",
  platform: "Android",
  osName: "Android",
  osVersion: "10",
  deviceManufacturer: "Google",
  deviceModel: "Google Pixel 4XL",
  deviceHardware: "Google Pixel 4XL",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "aba9031kl",
  appVersion: "1.42.3",
  carrier: "Omantel",
  connectionType: "wifi",
  effectiveConnectionType: "3g",
  meta: {
    "feature.testGroup": "beta"
  }
}, {
  abortChances: {
  },

  id: "4e8c9189-1737-4c78-bd18-24978a4dca56",
  fullName: "Alshama Fathima",
  email: "Alshamafathima433@gmail.com",
  ip: "149.200.128.23",
  language: "ar-JO",
  latitude : 30.5852,
  longitude :  36.2384,
  accuracyRadius : 5,
  country : "Jordan",
  countryCode : "JO",
  continent : "Asia",
  continentCode : "AS",
  platform: "iOS",
  osName: "iOS",
  osVersion: "16.7.1",
  deviceManufacturer: "Apple",
  deviceModel: "iPhone 13",
  deviceHardware: "iPhone14,5",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "aba9031kl",
  appVersion: "1.42.3",
  carrier: "Orange",
  connectionType: "wifi",
  effectiveConnectionType: "3g",
  meta: {
    "feature.testGroup": "sigma"
  }
}, {
  abortChances: {
  },

  id: "f0ea3830-7b6f-4f4b-ab78-c20ad7b46927",
  fullName: "Shehnaz Rehmat",
  email: "RehShenaz8993@gmail.com",
  ip: "115.85.132.57",
  language: "ar-AE",
  latitude : 25.2048,
  longitude :  55.2708,
  accuracyRadius : 5,
  country : "United Arab Emirates",
  countryCode : "AE",
  continent : "Asia",
  continentCode : "AS",
  platform: "Android",
  osName: "Android",
  osVersion: "10",
  deviceManufacturer: "Google",
  deviceModel: "Google Pixel 4XL",
  deviceHardware: "Google Pixel 4XL",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "aba9031kl",
  appVersion: "1.42.3",
  carrier: "Vodaphone",
  connectionType: "cellular",
  effectiveConnectionType: "3g",
  meta: {
    "feature.testGroup": "beta"
  }
}, {
  abortChances: {
  },

  id: "41c11dbc-a704-46a9-b3c8-fa2d744aa93e",
  fullName: "Mohammed Mikdhad",
  email: "Mohammedmikdhad@gmail.com",
  ip: "102.223.94.57",
  language: "ar-EG",
  latitude : 30.044,
  longitude :  31.2357,
  accuracyRadius : 5,
  country : "Egypt",
  countryCode : "EG",
  continent : "Asia",
  continentCode : "AS",
  platform: "Android",
  osName: "Android",
  osVersion: "10",
  deviceManufacturer: "Google",
  deviceModel: "Google Pixel 4XL",
  deviceHardware: "Google Pixel 4XL",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "aba9031kl",
  appVersion: "1.42.3",
  carrier: "Orange",
  connectionType: "wifi",
  effectiveConnectionType: "3g",
  meta: {
    "feature.testGroup": "beta"
  }
}, {
  abortChances: {
  },

  id: "46327d99-5c30-432f-957b-34bc32ec8fac",
  fullName: "Jaseer Khan",
  email: "Khanjasee@gmail.com",
  ip: "104.133.179.23",
  language: "ar-AE",
  latitude : 24.4539,
  longitude :  54.3773,
  accuracyRadius : 5,
  country : "United Arab Emirates",
  countryCode : "AE",
  continent : "Asia",
  continentCode : "AS",
  platform: "iOS",
  osName: "iOS",
  osVersion: "16.7.1",
  deviceManufacturer: "Apple",
  deviceModel: "iPhone 13",
  deviceHardware: "iPhone14,5",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "aba9031kl",
  appVersion: "1.42.3",
  carrier: "Vodaphone",
  connectionType: "cellular",
  effectiveConnectionType: "3g",
  meta: {
    "feature.testGroup": "alpha"
  }
}, {
  abortChances: {
  },

  id: "46327d99-5c30-432f-957b-34bc32ec8fac",
  fullName: "Khallefa Taj",
  email: "khallefa345@gmail.com",
  ip: "128.204.240.22",
  language: "ar-SA",
  latitude : 21.4858,
  longitude :  39.1925,
  accuracyRadius : 5,
  country : "Saudi Arabia",
  countryCode : "SA",
  continent : "Asia",
  continentCode : "AS",
  platform: "Android",
  osName: "Android",
  osVersion: "10",
  deviceManufacturer: "Google",
  deviceModel: "Google Pixel 4XL",
  deviceHardware: "Google Pixel 4XL",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "aba9031kl",
  appVersion: "1.42.3",
  carrier: "Saudi Telecom Company",
  connectionType: "cellular",
  effectiveConnectionType: "3g",
  meta: {
    "feature.testGroup": "beta"
  }
}, {
  abortChances: {
  },

  id: "46327d99-5c30-432f-957b-34bc32ec8fac",
  fullName: "Zehanaseeb Sayyid",
  email: "ZehanSayyid239@gmail.com",
  ip: "134.0.128.119",
  language: "ar-OM",
  latitude : 23.5880,
  longitude :  58.3829,
  accuracyRadius : 5,
  country : "Oman",
  countryCode : "OM",
  continent : "Asia",
  continentCode : "AS",
  platform: "Android",
  osName: "Android",
  osVersion: "10",
  deviceManufacturer: "Google",
  deviceModel: "Google Pixel 4XL",
  deviceHardware: "Google Pixel 4XL",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "aba9031kl",
  appVersion: "1.42.3",
  carrier: "Omantel",
  connectionType: "wifi",
  effectiveConnectionType: "3g",
  meta: {
    "feature.testGroup": "beta"
  }
}, {
  abortChances: {
  },

  id: "88ccee7a-724b-456d-943c-7fc2f87c5f3b",
  fullName: "Nihal Omarabdullah",
  email: "Nihalabdul@gmail.com",
  ip: "213.246.0.254",
  language: "ar-YE",
  latitude : 15.5527,
  longitude : 48.5164,
  accuracyRadius : 5,
  country : "Yemen",
  countryCode : "YE",
  continent : "Asia",
  continentCode : "AS",
  platform: "Android",
  osName: "Android",
  osVersion: "10",
  deviceManufacturer: "Google",
  deviceModel: "Google Pixel 4XL",
  deviceHardware: "Google Pixel 4XL",
  viewportWidth: 320,
  viewportHeight: 680,
  googlePlayServicesMissing: false,
  rooted: false,
  bundleIdentifier: "com.example.shop",
  appBuild: "aba9031kl",
  appVersion: "1.42.3",
  carrier: "Orange",
  connectionType: "wifi",
  effectiveConnectionType: "3g",
  meta: {
    "feature.testGroup": "beta"
  }
},
];
