
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install IBM Concert
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# --------------------------------------------------------------------------------------------------------------------------------------
# Install IBM Concert
# --------------------------------------------------------------------------------------------------------------------------------------

- name: 🛰️  START - INSTALL IBM Concert
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: Log
  shell: |
    export MESSAGE="Installing IBM Concert"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_feature.kind}}.log
  ignore_errors: true





- name: 🚀 IBM Concert - Set IBM Concert Password 
  set_fact: current_admin_pass={{global_config.global_password}}


- name: 🟣  IBM Concert -  IBM Concert Password {{current_admin_pass}}
  debug:
    var: current_admin_pass
    verbosity: 1






# --------------------------------------------------------------------------------------------------------------------------------------
# Getting Installation source from GitHub
# --------------------------------------------------------------------------------------------------------------------------------------
- name: 📣 OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification-status
    spec:
      backgroundColor: '#ffd500'
      color: '#000'
      location: {{global_config.position_ocp_notifications | default("BannerTop")}}
      text: 'Installing {{current_feature.kind}} - IBM Concert Getting Installation source from GitHub'    
    EOF
  ignore_errors: true
  args:
    executable: /bin/bash
  when: (global_config.create_ocp_notifications | default(true))|bool == true  





- name:   🚀 IBM Concert - Getting Installation source from GitHub
  shell: |
    echo "------------------------------------------------------------------------------------------------------------------------------"
    echo " 🚀 Getting Installation source from GitHub"
    echo "------------------------------------------------------------------------------------------------------------------------------"
    mkdir -p /tmp/
    cd  /tmp/

    wget https://github.com/IBM/Concert/releases/download/{{ current_feature.concert_version | default("v3.0.0") }}/ibm-concert-x86.tar.gz
    tar xfz ibm-concert-x86.tar.gz
    cd /tmp/ibm-concert
    # find . -type f -exec sed -i \
    # 's/rollout status Deployments,sts/rollout status Deployments/g' {} +

  register: output_string
  ignore_errors: true
  args:
    executable: /bin/bash

- name: 🟣  OUTPUT
  debug: 
    var: output_string.stdout_lines
    #verbosity: 1






# --------------------------------------------------------------------------------------------------------------------------------------
# Prepare Installation
# --------------------------------------------------------------------------------------------------------------------------------------
- name: 📣 OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification-status
    spec:
      backgroundColor: '#ffd500'
      color: '#000'
      location: {{global_config.position_ocp_notifications | default("BannerTop")}}
      text: 'Installing {{current_feature.kind}} - IBM Concert Prepare Installation'    
    EOF
  ignore_errors: true
  args:
    executable: /bin/bash
  when: (global_config.create_ocp_notifications | default(true))|bool == true  



- name:   🚀 IBM Concert - VARIABLES
  shell: |
    cd  /tmp/concert/ibm-concert
    echo ""
    echo ""
    echo ""
    echo ""
    echo "------------------------------------------------------------------------------------------------------------------------------"
    echo " 🚀 Variables"
    echo "------------------------------------------------------------------------------------------------------------------------------"
    echo "USER                  : admin"
    echo "PASSWORD:             : {{ global_config.global_password }}"
    echo "ENTITLED_REGISTRY_KEY : $ENTITLED_REGISTRY_KEY"
    echo ""
    echo ""
    echo ""
    echo ""
  register: output_string
  ignore_errors: true
  args:
    executable: /bin/bash

- name: 🟣  OUTPUT
  debug: 
    var: output_string.stdout_lines
    #verbosity: 1



- name:   🚀 IBM Concert - Prepare Installation
  shell: |
  

    export INSTALL_DIR=/tmp/ibm-concert


    export OCP_URL=$(oc get Infrastructure cluster -o jsonpath={.status.apiServerURL})
    echo "OCP_URL: $OCP_URL"
    mv /tmp/ibm-concert/etc/params.ini /tmp/ibm-concert/etc/params.ini.all
    cat > /tmp/ibm-concert/etc/params.ini <<EOF
    
    #cat concert-dataapps-workflows-k8s-params.ini
    # INSTALL_EKS: Set as True if installing on EKS
    INSTALL_EKS={{ current_feature.install_eks | default(false) }}
    # This example is to install Hub, Concert, Data Apps and Workflows on a Kubernetes cluster.
    REG_USER={{ current_feature.prod_user }}
    
    IMAGE_REGISTRY_PREFIX={{ current_feature.prod_registry }}


    # ----- Hub Configuration -----

    # OPTIONAL: 
    # For connecting installed product(s) to an existing remote Hub,
    # set HUB_URL and HUB_ACCESS_KEY parameters (details and examples in all-params.ini file).
    # If these parameters are not provided, local Hub will be automatically installed
    # HUB_URL=
    # HUB_ACCESS_KEY=

    # namespace for Hub
    HUB_NS={{ current_ibm_feature.project }}-hub
    HUB_IMAGE_REGISTRY_SUFFIX=/platform-hub
    # OPTIONAL: Set to 'true' to install additional local Hub components needed for integration with products like Turbonomic or Instana.
    ENABLE_CROSS_PRODUCT_INTEGRATION=true
    SCALE_CONFIG_HUB=level_1
    # storage class for Hub
    STORAGE_CLASS_HUB={{ STORAGE_CLASS_FILE }}



    # ----- Concert Configuration -----

    INSTALL_CONCERT={{ current_feature.install_concert | default(true) }}
    # namespace for Concert
    CONCERT_NS={{ current_ibm_feature.project }}
    CONCERT_IMAGE_REGISTRY_SUFFIX=/concert
    SCALE_CONFIG_CONCERT=level_1
    # storage class for Concert
    STORAGE_CLASS_CONCERT={{ STORAGE_CLASS_FILE }}


    # ----- Concert Secure Coder Configuration -----

    # Set to true to enable Concert buddy deployment
    ENABLE_BUDDY={{ current_feature.enable_buddy  | default(false) }}
    # Storage class (required if ENABLE_BUDDY is set to true)- pass the storage class name for Concert
    FILE_STORAGE_CLASS_CONCERT={{ STORAGE_CLASS_FILE }}
    INSTALL_SECURECODER={{ current_feature.install_secure_coder | default(false) }}


    # ----- Data Apps Configuration -----

    INSTALL_DATAAPPS={{ current_feature.install_dataapps | default(true) }}
    # namespace for Data Apps
    DATAAPPS_NS={{ current_ibm_feature.project }}-dataapps
    DATAAPPS_IMAGE_REGISTRY_SUFFIX=/concert
    SCALE_CONFIG_DATAAPPS=level_1
    # storage class for Dataapps
    STORAGE_CLASS_DATAAPPS={{ STORAGE_CLASS_FILE }}



    # ----- Concert Workflow Configuration -----

    INSTALL_WORKFLOWS={{ current_feature.install_workflows | default(true) }}
    WORKFLOWS_NS={{ current_ibm_feature.project }}-workflows
    # Domain name on which the application will listen
    # Example: solis-gw-workflows.apps.test.cp.my-domain.com
    WORKFLOWS_INSTANCE_ADDRESS=$OCP_URL
    # Takes a looooooot of time so set to false for the time being
    WORKFLOWS_INSTALL_ALL_INTEGRATIONS=false



    EOF

    echo "------------------------------------------------------------------------------------------------------------------------------"
    echo "------------------------------------------------------------------------------------------------------------------------------"
    echo "------------------------------------------------------------------------------------------------------------------------------"
    echo " 🛠️ Your Config File"
    echo "------------------------------------------------------------------------------------------------------------------------------"
    cat /tmp/ibm-concert/etc/params.ini
    echo "------------------------------------------------------------------------------------------------------------------------------"
    echo "------------------------------------------------------------------------------------------------------------------------------"
    echo "------------------------------------------------------------------------------------------------------------------------------"

  register: output_string
  ignore_errors: true
  args:
    executable: /bin/bash

- name: 🟣  OUTPUT
  debug: 
    var: output_string.stdout_lines
    #verbosity: 1



- name: 📣 OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification-status
    spec:
      backgroundColor: '#ff7700'
      color: '#000'
      location: {{global_config.position_ocp_notifications | default("BannerTop")}}
      text: 'Installing {{current_feature.kind}} - 🕦 Wait for IBM Concert to become ready (about 30-40 minutes) - Started at $(date +%H:%M) UTC'    
    EOF
  ignore_errors: true
  args:
    executable: /bin/bash
  when: (global_config.create_ocp_notifications | default(true))|bool == true  



- name:   🚀 IBM Concert -  Installation
  shell: |
    cd  /tmp/
    echo ""
    echo ""
    echo ""
    echo ""
    echo "------------------------------------------------------------------------------------------------------------------------------"
    echo " 🚀 Start Concert Installation"
    echo "------------------------------------------------------------------------------------------------------------------------------"
    echo "/tmp/bin/setup --license_acceptance=y --username=admin --password={{ global_config.global_password }} --registry_password=$ENTITLED_REGISTRY_KEY"
    /tmp/ibm-concert/bin/setup --license_acceptance=y --username=admin --password={{ global_config.global_password }} --registry_password=$ENTITLED_REGISTRY_KEY



  register: output_string
  ignore_errors: true
  args:
    executable: /bin/bash

- name: 🟣  OUTPUT
  debug: 
    var: output_string.stdout_lines
    #verbosity: 1



# - name: 🕦 CHECK -  Wait for all Pods in {{ current_ibm_feature.project }} to become ready (this might take some time)
#   shell: oc get pods -n ibm-concert -l app.kubernetes.io/name=ibm-concert|grep "Running"|grep "1/1"|wc -l| tr -d ' '
#   register: kubectl_get_pods
#   until: kubectl_get_pods.stdout|int > 17
#   retries: 500
#   delay: 15


- name: 📣 OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification-status
    spec:
      backgroundColor: '#ffd500'
      color: '#000'
      location: {{global_config.position_ocp_notifications | default("BannerTop")}}
      text: 'Installing {{current_feature.kind}} - IBM Concert Integfrate ITOM and TurboLite'    
    EOF
  ignore_errors: true
  args:
    executable: /bin/bash




- name:   🚀 IBM Concert - IBM Concert Integfrate ITOM and TurboLite
  shell: |
    export TURBO_URL=$(oc get route -n turbonomic nginx -o jsonpath={.spec.host})

    echo "------------------------------------------------------------------------------------------------------------------------------"
    echo " ✅ Register Turbo with ITOM"
    echo "------------------------------------------------------------------------------------------------------------------------------"
    export CONCERT_HUB_NAMESPACE={{ current_ibm_feature.project }}-hub
    export TURBOLITE_URL="https://$TURBO_URL"
    export TURBOLITE_USER="Administrator"
    export TURBOLITE_PASSWORD={{ global_config.global_password }}
    export APIKEY=$(kubectl -n "${CONCERT_HUB_NAMESPACE}" \
      get secret itom-secrets \
      -o jsonpath="{.data.BACKEND_APIKEY}" | base64 -d)
    
    echo "TURBO_URL:  $TURBO_URL"
    echo "CONCERT_HUB_NAMESPACE:  $CONCERT_HUB_NAMESPACE"
    echo "TURBOLITE_URL:  $TURBOLITE_URL"
    echo "TURBOLITE_USER:  $TURBOLITE_USER"
    echo "TURBOLITE_PASSWORD:  $TURBOLITE_PASSWORD"
    echo "APIKEY:  $APIKEY"

    kubectl -n "${CONCERT_HUB_NAMESPACE}" exec deployment/ibm-itom-data-model-backend -- \
    bash -c "curl -k -X POST https://localhost:7531/api/v1/registerGroupWithTurboLite \
      -H \"x-api-key: ${APIKEY}\" \
      -H 'Content-Type: application/json' \
      -d '{
        \"group_id\": \"0000-0000-0000-0000-default\",
        \"account_id\": \"0000-0000-0000-0000\",
        \"turbolite_endpoint\": \"${TURBOLITE_URL}\",
        \"turbolite_user\": \"${TURBOLITE_USER}\",
        \"turbolite_password\": \"${TURBOLITE_PASSWORD}\"
      }'"


    echo "------------------------------------------------------------------------------------------------------------------------------"
    echo " ✅ Register Turbo with Platform"
    echo "------------------------------------------------------------------------------------------------------------------------------"
    # Concert Observe: instana
    # Concert Optimize: turbonomic
    # Concert Protect and Concert Resilience: concert
    # Workflows: workflows
    # Data Apps: dataapps


    kubectl exec -it $(kubectl get pods -n ibm-installer | grep "ibm-install-concert" | awk '{print $1}') -n ibm-installer -- ls -al /tmp/ibm-concert/concert-hub/bin/
    kubectl exec -it $(kubectl get pods -n ibm-installer | grep "ibm-install-concert" | awk '{print $1}') -n ibm-installer -- /tmp/ibm-concert/concert-hub/bin/manage-product.sh --action=add --deployment-type=k8s --product-id=turbonomic --instance-url=https://$TURBO_URL --namespace={{ current_ibm_feature.project }}-hub --restart-hub=true


    echo "------------------------------------------------------------------------------------------------------------------------------"
    echo " ✅ Keycloak Credentials"
    echo "------------------------------------------------------------------------------------------------------------------------------"
    kubectl apply -f - <<EOF
    kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: kc
      namespace: ibm-concert-hub
    spec:
      to:
        kind: Service
        name: ibm-solis-hub-gw-svc
        weight: 100
      port:
        targetPort: external
      tls:
        termination: passthrough
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
    EOF


    export KC_USER=$(kubectl exec -it $(kubectl get pods -n ibm-concert-hub | grep "ibm-solis-embedded-keycloak" | awk '{print $1}') -n ibm-concert-hub -- env | grep 'KC_BOOTSTRAP_ADMIN_USERNAME='| cut -d= -f2)
    export KC_PWD=$(kubectl exec -it $(kubectl get pods -n ibm-concert-hub | grep "ibm-solis-embedded-keycloak" | awk '{print $1}') -n ibm-concert-hub -- env | grep 'KC_BOOTSTRAP_ADMIN_PASSWORD='| cut -d= -f2)
    export KC_ROUTE=$(oc get route kc -o jsonpath={.spec.host} -n $CONCERT_HUB_NAMESPACE)

    echo "KC_USER:        $KC_USER"
    echo "KC_PWD:         $KC_PWD"
    echo "KC_ROUTE:       https://$KC_ROUTE/sys/internal/kc"

  register: output_string
  ignore_errors: true
  args:
    executable: /bin/bash

- name: 🟣  OUTPUT
  debug: 
    var: output_string.stdout_lines
    #verbosity: 1





- name: 📣 OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification-status
    spec:
      backgroundColor: '#ff7700'
      color: '#000'
      location: {{global_config.position_ocp_notifications | default("BannerTop")}}
      text: 'Finalizing {{current_feature.kind}}'    
    EOF
  ignore_errors: true
  args:
    executable: /bin/bash
  when: (global_config.create_ocp_notifications | default(true))|bool == true  




- name:   🚀 IBM Concert -  Finalize
  shell: |
    cd  /tmp/concert/ibm-concert
    echo ""
    echo ""
    echo ""
    echo ""
    echo "------------------------------------------------------------------------------------------------------------------------------"
    echo " 🚀 Create Routes"
    echo "------------------------------------------------------------------------------------------------------------------------------"


    /tmp/ibm-concert/ibm-concert-k8s/ocp-route.sh {{ current_ibm_feature.project }}
    oc get route concert -n {{ current_ibm_feature.project }}
    oc extract -n {{ current_ibm_feature.project }} secret/app-cfg-secret --to=-

    /tmp/ibm-concert/ibm-dataapps-k8s/ocp-route.sh {{ current_ibm_feature.project }}-dataapps


    echo ""
    echo ""
    echo ""
    echo ""
    echo "------------------------------------------------------------------------------------------------------------------------------"
    echo " ✅ LOGINS"
    echo "------------------------------------------------------------------------------------------------------------------------------"
    



  register: output_string
  ignore_errors: true
  args:
    executable: /bin/bash

- name: 🟣  OUTPUT
  debug: 
    var: output_string.stdout_lines
    #verbosity: 1



