
apiVersion: batch/v1
kind: Job
metadata:
  name: load-log-indexes
  namespace: ibm-aiops-installer
spec:
  serviceAccountName: demo-admin
  template:
    spec:
      containers:
        - name: load
          image: quay.io/niklaushirt/ibm-aiops-tools:2.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "2024Mi"
              cpu: "1200m"
          command:
            - /bin/sh
            - -c
            - |
              #!/bin/bash
              #set -x

              echo "*****************************************************************************************************************************"
              echo " ✅ STARTING: Load log anomaly training files"
              echo "*****************************************************************************************************************************"

              echo "   ------------------------------------------------------------------------------------------------------------------------------"
              echo "    📥 Downloading log anomaly training files"
              echo "   ------------------------------------------------------------------------------------------------------------------------------"
              export AWX_REPO=https://github.com/niklaushirt/ibm-aiops-trainingdata.git
              git clone $AWX_REPO

              echo "   ------------------------------------------------------------------------------------------------------------------------------"
              echo "    🚀 Starting Data Load"
              echo "   ------------------------------------------------------------------------------------------------------------------------------"
              cd ibm-aiops-trainingdata
              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo "This Repo includes those latestet Commits"
              echo "------------------------------------------------------------------------------------------------------------------------------"
              git log|head -n 17
              echo ""
              echo ""

              ./training/load-logs-for-training.sh

              echo "*****************************************************************************************************************************"
              echo " ✅ DONE"
              echo "*****************************************************************************************************************************"
              sleep 60000

          env:
            - name: INDEX_OVERWRITE
              value : "true"
            - name: VERSION
              value : "latest"
      restartPolicy: Never

  backoffLimit: 4
