apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetoy-deployment1
  labels:
    app: kubetoy-app
spec:
    selector:
      matchLabels:
        app: kubetoy
    replicas: 1
    template:
      metadata:
        labels:
          app: kubetoy
      spec:
        containers:
        - name: kubetoy
          image: quay.io/niklaushirt/kubetoy:0.3
          resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "1"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3000
          volumeMounts:
          - name: configvol
            mountPath: /var/config
          - name: secretvol
            mountPath: /var/secret
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
          - name: ENV_TOY_CONFIGMAP
            valueFrom: 
              configMapKeyRef:
                name: kubetoy-configmap-env
                key: ENV_TOY_CONFIGMAP
          - name: ENV_TOY_SECRET
            valueFrom:
              secretKeyRef:
                name: kubetoy-secret-env
                key: ENV_TOY_SECRET
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        volumes:
        - name: configvol
          configMap:
            name: kubetoy-configmap-files
        - name: secretvol
          secret:
            secretName: kubetoy-secret-files