---
apiVersion: v1                     
kind: Namespace
metadata:
  name: eda
---  
kind: Secret
apiVersion: v1
metadata:
  name: docker-secret
  namespace: eda
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJuaWtsYXVzaGlydCIsInBhc3N3b3JkIjoiY29vbDk3IiwiZW1haWwiOiJuaWtsYXVzaGlydEBnbWFpbC5jb20iLCJhdXRoIjoiYm1scmJHRjFjMmhwY25RNlkyOXZiRGszIn19fQ==
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eda-admin
  namespace: eda
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eda-admin-crb
subjects:
  - kind: ServiceAccount
    name: eda-admin
    namespace: eda
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eda-instance
  namespace: eda
  labels:
      app: eda-instance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eda-instance
  template:
    metadata:
      labels:
        app: eda-instance
    spec:
      containers:
      - image: quay.io/niklaushirt/eda-container:0.1
        imagePullPolicy: Always
        name: eda-instance
        command:
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "250m"
            memory: "250Mi"

        env:
        - name: REPO_URL
          value: https://github.com/niklaushirt/ibm-aiops-eda.git
      serviceAccountName: eda-admin
      imagePullSecrets:
        - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: eda-instance-service
  namespace: eda
spec:
  selector:
    app: eda-instance
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: eda-instance
  namespace: eda
spec:
  path: /endpoint
  to:
    kind: Service
    name: eda-instance-service
    weight: 100
  port:
    targetPort: 5000
  wildcardPolicy: None