#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#     ________  __  ___   __________    ___         __                        __  _
#    /  _/ __ )/  |/  /  /  _/_  __/   /   | __  __/ /_____  ____ ___  ____ _/ /_(_)___  ____
#    / // __  / /|_/ /   / /  / /     / /| |/ / / / __/ __ \/ __ `__ \/ __ `/ __/ / __ \/ __ \
#  _/ // /_/ / /  / /  _/ /  / /     / ___ / /_/ / /_/ /_/ / / / / / / /_/ / /_/ / /_/ / / / /
# /___/_____/_/  /_/  /___/ /_/     /_/  |_\__,_/\__/\____/_/ /_/ /_/\__,_/\__/_/\____/_/ /_/
#
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  LOGS STREAMING POD
#
#  IBM AIOps
#
#  ©2024 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"


apiVersion: v1                     
kind: Namespace
metadata:
  name: ibm-aiops-installer
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ibm-aiops-installer-admin
  namespace: ibm-aiops-installer
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-aiops-installer-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: ibm-aiops-installer-admin
    namespace: ibm-aiops-installer
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-aiops-installer-default-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ibm-aiops-installer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ibm-aiops-installer
  name: ibm-aiops-logs-streaming
  annotations: {}
spec:
  selector:
    matchLabels:
      app: ibm-aiops-logs-streaming
  replicas: 1
  template:
    metadata:
      labels:
        app: ibm-aiops-logs-streaming
    spec:
      containers:
        - name: tools
          image: quay.io/niklaushirt/ibm-aiops-tools:2.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env: []
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "2024Mi"
              cpu: "1200m"
          command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              #set -x

              echo "*****************************************************************************************************************************"
              echo " ✅ STARTING: LOGS STREAMING POD"
              echo "*****************************************************************************************************************************"
              echo ""
              echo "  ⏳ INSTALLATION START TIMESTAMP: $(date)"
              echo ""
              echo "------------------------------------------------------------------------------------------------------------------------------"
    

              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo " 🚀 Getting Installation source from GitHub"
              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo "   📥 Clone Repo https://github.com/niklaushirt/ibm-aiops-deployer.git -b dev_latest"
              git clone https://github.com/niklaushirt/ibm-aiops-deployer.git -b dev_latest
              cd ibm-aiops-deployer

              echo ""
              echo ""
              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo "   🔎 This Repo includes those latestet Commits"
              git log|head -n 17
              echo ""
              echo ""

              echo ""
              echo ""
              echo "  ⏳ INSTALLATION END TIMESTAMP: $(date)"
              echo ""
              echo "*****************************************************************************************************************************"
              echo " ✅ INITIALIZATION - WAITING FOREVER"
              echo "*****************************************************************************************************************************"

              cd /ibm-aiops-deployer/tools/97_addons/ibm-aiops-custom-scenarios/synthetic-logs/
              rm templates/logs/logsbig.log
              rm /tmp/lags/logs.json 
              ./stream-logs.sh

              while true
              do
                sleep 1000
              done

      imagePullSecrets: []
  paused: false


